name: c-metadata-step
on: push
jobs:
  c:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Derive image tags
        id: meta
        if: github.event_name != 'pull_request'
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short
            type=raw,value=main,enable={{is_default_branch}}
      - run: echo "${{ steps.meta.outputs.tags }}"
